package migrate

// What the migrate probe (probe_test.go) found and the planner now does, each pinned as a
// minimal pair replayed against a real PostgreSQL the way roundTrip does: the DDL applies
// cleanly and reads back as the target.

import (
	"strings"
	"testing"
)

// A table that goes takes its triggers with it, but not their function: DROP FUNCTION must
// come after DROP TABLE (2BP01 "other objects depend on it" otherwise, measured).
func TestProbeTriggerFunctionDroppedAfterItsTable(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE keep (id integer PRIMARY KEY);
CREATE TABLE gone (id integer PRIMARY KEY, n integer);
CREATE FUNCTION gone_fn() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.n := 1; RETURN NEW; END $$;
CREATE TRIGGER gone_tr BEFORE INSERT ON gone FOR EACH ROW EXECUTE FUNCTION gone_fn();
`)
	to := mustCanonical(t, `
-- @migrate drop gone
CREATE TABLE keep (id integer PRIMARY KEY);
`)
	roundTrip(t, from, to, "", true)
}

// Changing the type of a column a generated column reads: PostgreSQL refuses the ALTER
// TYPE (0A000, measured) until the generated column is dropped, and it is re-added after,
// with the index and the CHECK over it.
func TestProbeTypeChangeUnderGeneratedColumn(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer NOT NULL, g bigint GENERATED ALWAYS AS (a + 1) STORED,
  CONSTRAINT t_g_check CHECK (g > 0));
CREATE INDEX t_g_idx ON t (g, id);
`)
	to := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a bigint NOT NULL, g bigint GENERATED ALWAYS AS (a + 1) STORED,
  CONSTRAINT t_g_check CHECK (g > 0));
CREATE INDEX t_g_idx ON t (g, id);
`)
	roundTrip(t, from, to, "", false)
}

// A new table with an identity column: the dump's ADD GENERATED ... AS IDENTITY among the
// table's ALTERs creates the sequence; emitting the sequence too is 0A000 "cannot change
// ownership of identity sequence" (measured).
func TestProbeNewTableWithIdentityColumn(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `CREATE TABLE keep (id integer PRIMARY KEY);`)
	to := mustCanonical(t, `
CREATE TABLE keep (id integer PRIMARY KEY);
CREATE TABLE fresh (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text);
`)
	roundTrip(t, from, to, "-- @migrate drop fresh", false)
}

// Columns added and dropped in dependency order: a generated column reading a column added
// alongside it after that column (42703 otherwise), and a gone generated column before the
// gone column it reads (2BP01 otherwise), both measured.
func TestProbeGeneratedColumnsOrderedByDependency(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `CREATE TABLE t (id integer PRIMARY KEY);`)
	to := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, g bigint GENERATED ALWAYS AS (x + 1) STORED, x integer);
`)
	roundTrip(t, from, to, "-- @migrate drop t.x\n-- @migrate drop t.g", false)
}

// A key another table's foreign key rests on cannot be dropped while the foreign key
// stands (2BP01, measured): the foreign key goes first and comes back once the target's
// key exists -- when the primary key moves off the referenced column, when the primary
// key constraint is renamed along with its table, and when the referencing table itself
// goes.
func TestProbeForeignKeyAroundDroppedKey(t *testing.T) {
	requirePgDump(t)
	t.Run("primary key moves", func(t *testing.T) {
		from := mustCanonical(t, `
CREATE TABLE parents (id integer PRIMARY KEY, code bigint NOT NULL);
CREATE TABLE children (id integer PRIMARY KEY, parent_id integer,
  CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES parents (id) ON DELETE SET NULL);
`)
		to := mustCanonical(t, `
CREATE TABLE parents (id integer NOT NULL, code bigint PRIMARY KEY, CONSTRAINT parents_id_key UNIQUE (id));
CREATE TABLE children (id integer PRIMARY KEY, parent_id integer,
  CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES parents (id) ON DELETE SET NULL);
`)
		roundTrip(t, from, to, "", false)
	})
	t.Run("primary key constraint renamed with its table", func(t *testing.T) {
		from := mustCanonical(t, `
CREATE TABLE parents (id integer PRIMARY KEY);
CREATE TABLE children (id integer PRIMARY KEY, parent_id integer,
  CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES parents (id));
`)
		to := mustCanonical(t, `
-- @migrate rename parents -> folks
CREATE TABLE folks (id integer NOT NULL, CONSTRAINT folks_pkey PRIMARY KEY (id));
CREATE TABLE children (id integer PRIMARY KEY, parent_id integer,
  CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES folks (id));
`)
		roundTrip(t, from, to, "-- @migrate rename folks -> parents", false)
	})
	t.Run("referencing table goes", func(t *testing.T) {
		from := mustCanonical(t, `
CREATE TABLE parents (id integer PRIMARY KEY, code bigint NOT NULL);
CREATE TABLE children (id integer PRIMARY KEY, parent_id integer,
  CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES parents (id));
`)
		to := mustCanonical(t, `
-- @migrate drop children
CREATE TABLE parents (id integer NOT NULL, code bigint PRIMARY KEY);
`)
		roundTrip(t, from, to, "", true)
	})
}

// A view over a table whose generated column is rewritten is recreated around the rewrite
// (the DROP COLUMN is 2BP01 while the view reads the column, measured); a generated
// expression that differs only by a declared rename is not rewritten at all (RENAME
// COLUMN carries it), so the view stays.
func TestProbeGeneratedRewriteWithDependentView(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer NOT NULL, b integer NOT NULL, g bigint GENERATED ALWAYS AS (a + 1) STORED);
CREATE VIEW v AS SELECT id, g FROM t;
`)
	t.Run("expression changes", func(t *testing.T) {
		to := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer NOT NULL, b integer NOT NULL, g bigint GENERATED ALWAYS AS (b + 1) STORED);
CREATE VIEW v AS SELECT id, g FROM t;
`)
		roundTrip(t, from, to, "", false)
	})
	t.Run("read column renamed", func(t *testing.T) {
		to := mustCanonical(t, `
-- @migrate rename t.a -> t.alpha
CREATE TABLE t (id integer PRIMARY KEY, alpha integer NOT NULL, b integer NOT NULL, g bigint GENERATED ALWAYS AS (alpha + 1) STORED);
CREATE VIEW v AS SELECT id, g FROM t;
`)
		plan, err := Plan(from.s, to.s, to.intents)
		if err != nil {
			t.Fatal(err)
		}
		for _, s := range plan {
			if strings.Contains(s, "DROP COLUMN") {
				t.Errorf("a rename alone must not rewrite the generated column:\n%s", s)
			}
		}
		roundTrip(t, from, to, "-- @migrate rename t.alpha -> t.a", false)
	})
}

// A replaced view whose new definition reads a column the plan adds is replaced after the
// ADD COLUMN (42703 otherwise, measured); a view an ENUM recreation already dropped is
// created once, not replaced and then created (42P07 otherwise, measured).
func TestProbeReplacedViewOrder(t *testing.T) {
	requirePgDump(t)
	t.Run("reads an added column", func(t *testing.T) {
		from := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer);
CREATE VIEW v AS SELECT id, a FROM t;
`)
		to := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer, b integer);
CREATE VIEW v AS SELECT id, a, b FROM t;
`)
		roundTrip(t, from, to, "-- @migrate drop t.b", true)
	})
	t.Run("recreated by an enum label drop", func(t *testing.T) {
		from := mustCanonical(t, `
CREATE TYPE mood AS ENUM ('ok', 'meh');
CREATE TABLE t (id integer PRIMARY KEY, m mood, a integer);
CREATE VIEW v AS SELECT id FROM t;
`)
		to := mustCanonical(t, `
-- @migrate enum mood: drop 'meh' using 'ok'
CREATE TYPE mood AS ENUM ('ok');
CREATE TABLE t (id integer PRIMARY KEY, m mood, a integer);
CREATE VIEW v AS SELECT id, a FROM t;
`)
		roundTrip(t, from, to, "", true)
	})
}

// A column rename whose right side names the table as it will be, declared before the
// table's own rename: the table renames are read first whatever their line.
func TestProbeColumnRenameNamesRenamedTable(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `CREATE TABLE t (id integer PRIMARY KEY, a integer);`)
	to := mustCanonical(t, `
-- @migrate rename t.a -> u.b
-- @migrate rename t -> u
CREATE TABLE u (id integer PRIMARY KEY, b integer);
`)
	roundTrip(t, from, to, "-- @migrate rename u.b -> t.a\n-- @migrate rename u -> t", false)
}

// A comment on a table that is renamed is the same comment under the new name; one the
// target no longer declares is removed under the new name (measured: it stayed before).
func TestProbeCommentFollowsRename(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer);
COMMENT ON TABLE t IS 'about t';
COMMENT ON COLUMN t.a IS 'a';
`)
	t.Run("kept", func(t *testing.T) {
		to := mustCanonical(t, `
-- @migrate rename t -> u
CREATE TABLE u (id integer PRIMARY KEY, a integer);
COMMENT ON TABLE u IS 'about t';
COMMENT ON COLUMN u.a IS 'a';
`)
		plan, err := Plan(from.s, to.s, to.intents)
		if err != nil {
			t.Fatal(err)
		}
		for _, s := range plan {
			if strings.HasPrefix(s, "COMMENT ON") {
				t.Errorf("an unchanged comment on a renamed table is not re-issued: %s", s)
			}
		}
		roundTrip(t, from, to, "-- @migrate rename u -> t", false)
	})
	t.Run("dropped", func(t *testing.T) {
		to := mustCanonical(t, `
-- @migrate rename t -> u
CREATE TABLE u (id integer PRIMARY KEY, a integer);
`)
		roundTrip(t, from, to, "-- @migrate rename u -> t", false)
	})
}

// A serial column's sequence keeps its name when its table or column is renamed, while the
// target (a fresh CREATE) names it after the new names: the plan renames the sequence too
// (the SET DEFAULT nextval('<new>_seq') it emits is 42P01 otherwise, measured). An
// identity column's sequence is the server's own and is left alone.
func TestProbeSerialSequenceFollowsRename(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `CREATE TABLE t (id bigserial PRIMARY KEY, n bigserial, a integer);`)
	t.Run("table", func(t *testing.T) {
		to := mustCanonical(t, "-- @migrate rename t -> u\nCREATE TABLE u (id bigserial PRIMARY KEY, n bigserial, a integer);")
		roundTrip(t, from, to, "-- @migrate rename u -> t", false)
	})
	t.Run("column", func(t *testing.T) {
		to := mustCanonical(t, "-- @migrate rename t.n -> t.m\nCREATE TABLE t (id bigserial PRIMARY KEY, m bigserial, a integer);")
		roundTrip(t, from, to, "-- @migrate rename t.m -> t.n", false)
	})
}
