package migrate

// What the migrate probe (probe_test.go) found and the planner now does, each pinned as a
// minimal pair replayed against a real PostgreSQL the way roundTrip does: the DDL applies
// cleanly and reads back as the target.

import (
	"strings"
	"testing"
)

// A table that goes takes its triggers with it, but not their function: DROP FUNCTION must
// come after DROP TABLE (2BP01 "other objects depend on it" otherwise, measured).
func TestProbeTriggerFunctionDroppedAfterItsTable(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE keep (id integer PRIMARY KEY);
CREATE TABLE gone (id integer PRIMARY KEY, n integer);
CREATE FUNCTION gone_fn() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.n := 1; RETURN NEW; END $$;
CREATE TRIGGER gone_tr BEFORE INSERT ON gone FOR EACH ROW EXECUTE FUNCTION gone_fn();
`)
	to := mustCanonical(t, `
-- @migrate drop gone
CREATE TABLE keep (id integer PRIMARY KEY);
`)
	roundTrip(t, from, to, "", true)
}

// Changing the type of a column a generated column reads: PostgreSQL refuses the ALTER
// TYPE (0A000, measured) until the generated column is dropped, and it is re-added after,
// with the index and the CHECK over it.
func TestProbeTypeChangeUnderGeneratedColumn(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer NOT NULL, g bigint GENERATED ALWAYS AS (a + 1) STORED,
  CONSTRAINT t_g_check CHECK (g > 0));
CREATE INDEX t_g_idx ON t (g, id);
`)
	to := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a bigint NOT NULL, g bigint GENERATED ALWAYS AS (a + 1) STORED,
  CONSTRAINT t_g_check CHECK (g > 0));
CREATE INDEX t_g_idx ON t (g, id);
`)
	roundTrip(t, from, to, "", false)
}

// A new table with an identity column: the dump's ADD GENERATED ... AS IDENTITY among the
// table's ALTERs creates the sequence; emitting the sequence too is 0A000 "cannot change
// ownership of identity sequence" (measured).
func TestProbeNewTableWithIdentityColumn(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `CREATE TABLE keep (id integer PRIMARY KEY);`)
	to := mustCanonical(t, `
CREATE TABLE keep (id integer PRIMARY KEY);
CREATE TABLE fresh (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text);
`)
	roundTrip(t, from, to, "-- @migrate drop fresh", false)
}

// Columns added and dropped in dependency order: a generated column reading a column added
// alongside it after that column (42703 otherwise), and a gone generated column before the
// gone column it reads (2BP01 otherwise), both measured.
func TestProbeGeneratedColumnsOrderedByDependency(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `CREATE TABLE t (id integer PRIMARY KEY);`)
	to := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, g bigint GENERATED ALWAYS AS (x + 1) STORED, x integer);
`)
	roundTrip(t, from, to, "-- @migrate drop t.x\n-- @migrate drop t.g", false)
}

// A key another table's foreign key rests on cannot be dropped while the foreign key
// stands (2BP01, measured): the foreign key goes first and comes back once the target's
// key exists -- when the primary key moves off the referenced column, when the primary
// key constraint is renamed along with its table, and when the referencing table itself
// goes.
func TestProbeForeignKeyAroundDroppedKey(t *testing.T) {
	requirePgDump(t)
	t.Run("primary key moves", func(t *testing.T) {
		from := mustCanonical(t, `
CREATE TABLE parents (id integer PRIMARY KEY, code bigint NOT NULL);
CREATE TABLE children (id integer PRIMARY KEY, parent_id integer,
  CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES parents (id) ON DELETE SET NULL);
`)
		to := mustCanonical(t, `
CREATE TABLE parents (id integer NOT NULL, code bigint PRIMARY KEY, CONSTRAINT parents_id_key UNIQUE (id));
CREATE TABLE children (id integer PRIMARY KEY, parent_id integer,
  CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES parents (id) ON DELETE SET NULL);
`)
		roundTrip(t, from, to, "", false)
	})
	t.Run("primary key constraint renamed with its table", func(t *testing.T) {
		from := mustCanonical(t, `
CREATE TABLE parents (id integer PRIMARY KEY);
CREATE TABLE children (id integer PRIMARY KEY, parent_id integer,
  CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES parents (id));
`)
		to := mustCanonical(t, `
-- @migrate rename parents -> folks
CREATE TABLE folks (id integer NOT NULL, CONSTRAINT folks_pkey PRIMARY KEY (id));
CREATE TABLE children (id integer PRIMARY KEY, parent_id integer,
  CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES folks (id));
`)
		roundTrip(t, from, to, "-- @migrate rename folks -> parents", false)
	})
	t.Run("referencing table goes", func(t *testing.T) {
		from := mustCanonical(t, `
CREATE TABLE parents (id integer PRIMARY KEY, code bigint NOT NULL);
CREATE TABLE children (id integer PRIMARY KEY, parent_id integer,
  CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES parents (id));
`)
		to := mustCanonical(t, `
-- @migrate drop children
CREATE TABLE parents (id integer NOT NULL, code bigint PRIMARY KEY);
`)
		roundTrip(t, from, to, "", true)
	})
}

// A view over a table whose generated column is rewritten is recreated around the rewrite
// (the DROP COLUMN is 2BP01 while the view reads the column, measured); a generated
// expression that differs only by a declared rename is not rewritten at all (RENAME
// COLUMN carries it), so the view stays.
func TestProbeGeneratedRewriteWithDependentView(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer NOT NULL, b integer NOT NULL, g bigint GENERATED ALWAYS AS (a + 1) STORED);
CREATE VIEW v AS SELECT id, g FROM t;
`)
	t.Run("expression changes", func(t *testing.T) {
		to := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer NOT NULL, b integer NOT NULL, g bigint GENERATED ALWAYS AS (b + 1) STORED);
CREATE VIEW v AS SELECT id, g FROM t;
`)
		roundTrip(t, from, to, "", false)
	})
	t.Run("read column renamed", func(t *testing.T) {
		to := mustCanonical(t, `
-- @migrate rename t.a -> t.alpha
CREATE TABLE t (id integer PRIMARY KEY, alpha integer NOT NULL, b integer NOT NULL, g bigint GENERATED ALWAYS AS (alpha + 1) STORED);
CREATE VIEW v AS SELECT id, g FROM t;
`)
		plan, err := Plan(from.s, to.s, to.intents)
		if err != nil {
			t.Fatal(err)
		}
		for _, s := range plan {
			if strings.Contains(s, "DROP COLUMN") {
				t.Errorf("a rename alone must not rewrite the generated column:\n%s", s)
			}
		}
		roundTrip(t, from, to, "-- @migrate rename t.alpha -> t.a", false)
	})
}

// A replaced view whose new definition reads a column the plan adds is replaced after the
// ADD COLUMN (42703 otherwise, measured); a view an ENUM recreation already dropped is
// created once, not replaced and then created (42P07 otherwise, measured).
func TestProbeReplacedViewOrder(t *testing.T) {
	requirePgDump(t)
	t.Run("reads an added column", func(t *testing.T) {
		from := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer);
CREATE VIEW v AS SELECT id, a FROM t;
`)
		to := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer, b integer);
CREATE VIEW v AS SELECT id, a, b FROM t;
`)
		roundTrip(t, from, to, "-- @migrate drop t.b", true)
	})
	t.Run("recreated by an enum label drop", func(t *testing.T) {
		from := mustCanonical(t, `
CREATE TYPE mood AS ENUM ('ok', 'meh');
CREATE TABLE t (id integer PRIMARY KEY, m mood, a integer);
CREATE VIEW v AS SELECT id FROM t;
`)
		to := mustCanonical(t, `
-- @migrate enum mood: drop 'meh' using 'ok'
CREATE TYPE mood AS ENUM ('ok');
CREATE TABLE t (id integer PRIMARY KEY, m mood, a integer);
CREATE VIEW v AS SELECT id, a FROM t;
`)
		roundTrip(t, from, to, "", true)
	})
}

// A column rename whose right side names the table as it will be, declared before the
// table's own rename: the table renames are read first whatever their line.
func TestProbeColumnRenameNamesRenamedTable(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `CREATE TABLE t (id integer PRIMARY KEY, a integer);`)
	to := mustCanonical(t, `
-- @migrate rename t.a -> u.b
-- @migrate rename t -> u
CREATE TABLE u (id integer PRIMARY KEY, b integer);
`)
	roundTrip(t, from, to, "-- @migrate rename u.b -> t.a\n-- @migrate rename u -> t", false)
}

// A comment on a table that is renamed is the same comment under the new name; one the
// target no longer declares is removed under the new name (measured: it stayed before).
func TestProbeCommentFollowsRename(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer);
COMMENT ON TABLE t IS 'about t';
COMMENT ON COLUMN t.a IS 'a';
`)
	t.Run("kept", func(t *testing.T) {
		to := mustCanonical(t, `
-- @migrate rename t -> u
CREATE TABLE u (id integer PRIMARY KEY, a integer);
COMMENT ON TABLE u IS 'about t';
COMMENT ON COLUMN u.a IS 'a';
`)
		plan, err := Plan(from.s, to.s, to.intents)
		if err != nil {
			t.Fatal(err)
		}
		for _, s := range plan {
			if strings.HasPrefix(s, "COMMENT ON") {
				t.Errorf("an unchanged comment on a renamed table is not re-issued: %s", s)
			}
		}
		roundTrip(t, from, to, "-- @migrate rename u -> t", false)
	})
	t.Run("dropped", func(t *testing.T) {
		to := mustCanonical(t, `
-- @migrate rename t -> u
CREATE TABLE u (id integer PRIMARY KEY, a integer);
`)
		roundTrip(t, from, to, "-- @migrate rename u -> t", false)
	})
}

// A serial column's sequence keeps its name when its table or column is renamed, while the
// target (a fresh CREATE) names it after the new names: the plan renames the sequence too
// (the SET DEFAULT nextval('<new>_seq') it emits is 42P01 otherwise, measured). An
// identity column's sequence is the server's own and is left alone.
func TestProbeSerialSequenceFollowsRename(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `CREATE TABLE t (id bigserial PRIMARY KEY, n bigserial, a integer);`)
	t.Run("table", func(t *testing.T) {
		to := mustCanonical(t, "-- @migrate rename t -> u\nCREATE TABLE u (id bigserial PRIMARY KEY, n bigserial, a integer);")
		roundTrip(t, from, to, "-- @migrate rename u -> t", false)
	})
	t.Run("column", func(t *testing.T) {
		to := mustCanonical(t, "-- @migrate rename t.n -> t.m\nCREATE TABLE t (id bigserial PRIMARY KEY, m bigserial, a integer);")
		roundTrip(t, from, to, "-- @migrate rename t.m -> t.n", false)
	})
}

// A composite type's ALTER ATTRIBUTE TYPE goes through the same catalog check as ALTER
// COLUMN TYPE (find_composite_type_dependencies) and PostgreSQL refuses it while any
// column, anywhere, has the type (0A000 "cannot alter type ... because column ... uses
// it", measured) -- unlike ADD / DROP ATTRIBUTE, which touch no stored value and go
// through untouched (also measured, against a table holding a row of the type). There is
// no rewrite to offer in ALTER ATTRIBUTE TYPE's place (the column would need to be
// dropped and re-added, which loses data), so the plan reports it as a problem instead of
// DDL PostgreSQL would refuse.
func TestProbeCompositeAlterAttributeTypeWhileColumnUsesIt(t *testing.T) {
	requirePgDump(t)
	t.Run("used: a problem, not DDL", func(t *testing.T) {
		from := mustCanonical(t, `
CREATE TYPE pt AS (x integer, y integer);
CREATE TABLE t (id integer PRIMARY KEY, p pt NOT NULL);
`)
		to := mustCanonical(t, `
CREATE TYPE pt AS (x bigint, y integer);
CREATE TABLE t (id integer PRIMARY KEY, p pt NOT NULL);
`)
		_, err := Plan(from.s, to.s, to.intents)
		if err == nil || !strings.Contains(err.Error(), "attribute x changes type") || !strings.Contains(err.Error(), "a column uses the type") {
			t.Errorf("got %v\nwant a problem naming the column that uses the type", err)
		}
	})
	t.Run("unused: ALTER ATTRIBUTE TYPE", func(t *testing.T) {
		from := mustCanonical(t, `CREATE TYPE pt AS (x integer, y integer);`)
		to := mustCanonical(t, `CREATE TYPE pt AS (x bigint, y integer);`)
		roundTrip(t, from, to, "", false)
	})
	t.Run("used: ADD / DROP ATTRIBUTE still plan and apply", func(t *testing.T) {
		from := mustCanonical(t, `
CREATE TYPE pt AS (x integer, y integer);
CREATE TABLE t (id integer PRIMARY KEY, p pt NOT NULL);
`)
		to := mustCanonical(t, `
CREATE TYPE pt AS (x integer, z text);
CREATE TABLE t (id integer PRIMARY KEY, p pt NOT NULL);
`)
		roundTrip(t, from, to, "", true)
	})
}

// An EXCLUDE constraint on a generated column is a table constraint "defined solely on
// this column" the same way a UNIQUE or CHECK is: dropGenerated's DROP COLUMN takes it
// down silently, but addGenerated only put PRIMARY KEY / UNIQUE / CHECK back
// (soleColumnConstraints), leaving the EXCLUDE gone (measured: the plan's DDL applied but
// left "+ constraint" in the diff -- it never came back).
func TestProbeExcludeRestoredAfterGeneratedRewrite(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer NOT NULL, g bigint GENERATED ALWAYS AS (a + 1) STORED,
  CONSTRAINT t_g_excl EXCLUDE USING btree (g WITH =));
`)
	to := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a bigint NOT NULL, g bigint GENERATED ALWAYS AS (a + 1) STORED,
  CONSTRAINT t_g_excl EXCLUDE USING btree (g WITH =));
`)
	roundTrip(t, from, to, "", false)
}

// A row-level security policy's USING / WITH CHECK reading a column blocks ALTER COLUMN
// TYPE the same way a generated column's expression does (0A000 "cannot alter type of a
// column used in a policy definition", measured), whether or not the policy itself
// changes: the plan drops it and recreates it around the ALTER.
func TestProbePolicyAroundColumnTypeChange(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer);
ALTER TABLE t ENABLE ROW LEVEL SECURITY;
CREATE POLICY pol ON t USING (a > 0) WITH CHECK (a > 0);
`)
	to := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a bigint);
ALTER TABLE t ENABLE ROW LEVEL SECURITY;
CREATE POLICY pol ON t USING (a > 0) WITH CHECK (a > 0);
`)
	roundTrip(t, from, to, "", false)
}

// The same refusal ALTER COLUMN TYPE meets from a policy also comes from a RULE that
// reads the column ("cannot alter type of a column used by a view or rule", 0A000,
// measured): the plan drops it and recreates it around the ALTER, the same way as a
// policy -- found and fixed together, pinned separately since a rule's condition is
// unanalyzed AST (matched by deparsed text) rather than a policy's schema.Expr.
func TestProbeRuleAroundColumnTypeChange(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer);
CREATE RULE r AS ON INSERT TO t WHERE (a > 0) DO ALSO NOTHING;
`)
	to := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a bigint);
CREATE RULE r AS ON INSERT TO t WHERE (a > 0) DO ALSO NOTHING;
`)
	roundTrip(t, from, to, "", false)
}

// A rule that already gets its own DROP RULE / CREATE RULE elsewhere in the plan (here,
// because the table it is on renames, which the rule's deparsed definition reads into,
// making it differ from the from-side rule of the same name) must not also go through
// the column-type-change drop/recreate above: a second DROP RULE for the same rule is
// 42704 "rule ... does not exist" (measured), since the first one already ran it.
func TestProbeRuleNotDroppedTwiceAroundRenameAndTypeChange(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, a integer);
CREATE RULE r AS ON INSERT TO t WHERE (a > 0) DO ALSO NOTHING;
`)
	to := mustCanonical(t, `
-- @migrate rename t -> u
CREATE TABLE u (id integer PRIMARY KEY, a bigint);
CREATE RULE r AS ON INSERT TO u WHERE (a > 0) DO ALSO NOTHING;
`)
	roundTrip(t, from, to, "-- @migrate rename u -> t", true)
}

// DROP SCHEMA must come after the ALTER TABLE ... SET SCHEMA that empties it of the
// table declared to move out (-- @migrate rename): dropSchemas (from-side view of what
// is "still in" a schema) ran inside drops(), before renames() moved the table, so it
// saw the table as still there and it was 2BP01 "other objects depend on it" (measured).
func TestProbeDropSchemaAfterTableMovesOut(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE SCHEMA app;
CREATE TABLE app.t (id integer PRIMARY KEY);
`)
	to := mustCanonical(t, `
-- @migrate rename app.t -> public.t
CREATE TABLE public.t (id integer PRIMARY KEY);
`)
	roundTrip(t, from, to, "", true)
}

// The mirror image of DROP SCHEMA's ordering bug: CREATE SCHEMA must come before the
// ALTER TABLE ... SET SCHEMA that moves a table into it, but it was emitted from adds(),
// which runs after renames() -- 3F000 "schema does not exist" (measured).
func TestProbeCreateSchemaBeforeTableMovesIn(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `CREATE TABLE public.t (id integer PRIMARY KEY);`)
	to := mustCanonical(t, `
-- @migrate rename public.t -> app.t
CREATE SCHEMA app;
CREATE TABLE app.t (id integer PRIMARY KEY);
`)
	roundTrip(t, from, to, "", true)
}

// ALTER TABLE ... SET SCHEMA already carries an owned sequence (bigserial / IDENTITY)
// with it when the sequence starts out in its owning table's own schema: a separate
// ALTER SEQUENCE ... SET SCHEMA for it, emitted because the table's rename also moves
// the sequence's declared owner, found nothing left in the old schema to move (42P01
// "relation does not exist", measured).
func TestProbeOwnedSequenceFollowsTableSchemaMove(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE SCHEMA app;
CREATE TABLE app.t (id bigserial PRIMARY KEY);
`)
	to := mustCanonical(t, `
-- @migrate rename app.t -> public.t
CREATE TABLE public.t (id bigserial PRIMARY KEY);
`)
	roundTrip(t, from, to, "-- @migrate rename public.t -> app.t", false)
}

// --- partitioning (brief-partition-pg.md / brief-partition-common.md) --------------------

// A brand-new partitioned table with its partitions: pg_dump (and so this plan's always-
// canonical inputs) never spells a partition as a single CREATE TABLE ... PARTITION OF ...
// FOR VALUES ...; it is a plain CREATE TABLE plus a later ALTER TABLE ... ATTACH PARTITION
// naming the *parent*. Replaying that ALTER inline with the parent's own CREATE TABLE (the
// schema.Relation.Alters it was recorded under) ran before the child's own CREATE TABLE
// existed (42P01, measured) -- migrate.go now synthesizes ATTACH PARTITION itself, once
// every new table exists.
func TestProbeNewPartitionedTableAttachOrder(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `CREATE TABLE keep (id integer PRIMARY KEY);`)
	to := mustCanonical(t, `
CREATE TABLE keep (id integer PRIMARY KEY);
CREATE TABLE p (id integer NOT NULL) PARTITION BY RANGE (id);
CREATE TABLE p_1 PARTITION OF p FOR VALUES FROM (1) TO (10);
CREATE TABLE p_default PARTITION OF p DEFAULT;
`)
	roundTrip(t, from, to, "-- @migrate drop p\n-- @migrate drop p_1\n-- @migrate drop p_default", false)
}

// A partition's bound moved, and another partition detached in the same plan: every
// DETACH in the plan must precede every ATTACH, not just the same partition's own -- an
// incoming bound can overlap another partition's outgoing one otherwise (23514 "would
// overlap", measured, when a wider bound landed before the sibling's own DETACH).
func TestProbePartitionBoundMoveAndDetachOrdering(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE p (id integer NOT NULL) PARTITION BY RANGE (id);
CREATE TABLE p_1 PARTITION OF p FOR VALUES FROM (1) TO (10);
CREATE TABLE p_2 PARTITION OF p FOR VALUES FROM (10) TO (20);
`)
	to := mustCanonical(t, `
CREATE TABLE p (id integer NOT NULL) PARTITION BY RANGE (id);
CREATE TABLE p_1 PARTITION OF p FOR VALUES FROM (1) TO (15);
CREATE TABLE p_2 (id integer NOT NULL);
`)
	roundTrip(t, from, to, "", true)
}

// A new partition attached to a parent that already has a PRIMARY KEY and an index:
// PostgreSQL's own ATTACH PARTITION immediately builds and attaches a matching PRIMARY
// KEY and index on the incoming partition (unlike attaching to a parent created fresh in
// the same plan, which has neither yet) -- the plan's own explicit ADD CONSTRAINT /
// CREATE INDEX for the same shape is then 42P16 "multiple primary keys" (measured).
func TestProbeAttachPartitionUnderKeyedParent(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE p (id integer NOT NULL PRIMARY KEY) PARTITION BY RANGE (id);
CREATE TABLE p_1 PARTITION OF p FOR VALUES FROM (1) TO (10);
CREATE TABLE p_new (id integer NOT NULL PRIMARY KEY);
`)
	to := mustCanonical(t, `
CREATE TABLE p (id integer NOT NULL PRIMARY KEY) PARTITION BY RANGE (id);
CREATE TABLE p_1 PARTITION OF p FOR VALUES FROM (1) TO (10);
CREATE TABLE p_new PARTITION OF p FOR VALUES FROM (10) TO (20);
`)
	roundTrip(t, from, to, "", true)
}

// A column dropped from a table that survives, and that no longer-owned column happened
// to own a standalone sequence which the target still keeps (unowned): PostgreSQL drops
// a column-owned sequence along with the column itself (measured, not merely clearing its
// ownership) -- the plan's own ALTER SEQUENCE ... OWNED BY NONE, unconditionally emitted
// whenever a surviving sequence's OwnedBy differs, then found nothing left (42P01). The
// sequence needs recreating instead once its owning column is genuinely dropped, not
// renamed (ownerColumnStatus's ownerColumnGoneNotTable case).
func TestProbeSequenceRecreatedAfterOwningColumnDropped(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE t (id integer PRIMARY KEY, r integer);
CREATE SEQUENCE sq;
ALTER SEQUENCE sq OWNED BY t.r;
`)
	to := mustCanonical(t, `
-- @migrate drop t.r
CREATE TABLE t (id integer PRIMARY KEY);
CREATE SEQUENCE sq;
`)
	roundTrip(t, from, to, "", true)
}

// A sequence reassigned to a new owner while its old owning *table* is dropped in the same
// plan: drops() already clears the sequence's OWNED BY (ALTER SEQUENCE ... OWNED BY NONE)
// ahead of that table's own DROP TABLE, since alters() only reaches surviving tables --
// but alters() then left it at NONE rather than the target's actual new owner, since it
// saw the sequence's own OWNED BY change and assumed nothing needed doing once the old
// owning table was gone.
func TestProbeSequenceReownedWhileOldOwnerTableDrops(t *testing.T) {
	requirePgDump(t)
	from := mustCanonical(t, `
CREATE TABLE keep (id integer PRIMARY KEY, c integer);
CREATE TABLE gone (id integer PRIMARY KEY, r integer);
CREATE SEQUENCE sq;
ALTER SEQUENCE sq OWNED BY gone.r;
`)
	to := mustCanonical(t, `
-- @migrate drop gone
CREATE TABLE keep (id integer PRIMARY KEY, c integer);
CREATE SEQUENCE sq;
ALTER SEQUENCE sq OWNED BY keep.c;
`)
	roundTrip(t, from, to, "", true)
}

// pg_dump attaches a partition's own index to the parent's partitioned index with
// ALTER INDEX ... ATTACH PARTITION, an AlterTableStmt whose Objtype is OBJECT_INDEX
// (schema.go's generic ALTER TABLE dispatch looked up the *index* name as if it were a
// relation and refused it as "does not exist", measured) rather than OBJECT_TABLE; a
// partitioned schema's own dump could not even load.
func TestProbeAlterIndexAttachPartitionLoads(t *testing.T) {
	requirePgDump(t)
	// no roundTrip: this is a loader-only regression (mustCanonical itself is the
	// assertion -- it fails the test if the schema does not load).
	mustCanonical(t, `
CREATE TABLE p (id integer NOT NULL, n integer) PARTITION BY RANGE (id);
CREATE TABLE p_1 PARTITION OF p FOR VALUES FROM (1) TO (10);
CREATE INDEX p_n_idx ON p (n);
`)
}
