package cli

import (
	"context"
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/kr9ly/sqlshape/internal/dump"
	"github.com/kr9ly/sqlshape/internal/pgparse"
)

// warnServerVersion tells the user when the database at connString runs another PostgreSQL
// major version than schema.sql declares: the DDL is still derived and applied, judged by the
// declared version's rules, but the difference is worth knowing before it runs there. A
// database that cannot be asked is left to the step that follows, which reports its own error.
func warnServerVersion(ctx context.Context, stderr io.Writer, connString string, declared pgparse.Version) {
	server, err := dump.ServerVersion(ctx, connString)
	if err != nil {
		return
	}
	if msg := versionMismatch(declared, server); msg != "" {
		fmt.Fprintln(stderr, "sqlshape: warning: "+msg)
	}
}

// versionMismatch is the warning for a server version ("17.5", "18beta1") that is not the
// declared major, or "" when they agree.
func versionMismatch(declared pgparse.Version, server string) string {
	digits := strings.TrimLeftFunc(server, func(r rune) bool { return r < '0' || r > '9' })
	i := strings.IndexFunc(digits, func(r rune) bool { return r < '0' || r > '9' })
	if i >= 0 {
		digits = digits[:i]
	}
	major, err := strconv.Atoi(digits)
	if err != nil || major == int(declared.Or()) {
		return ""
	}
	return fmt.Sprintf("the database runs PostgreSQL %s but schema.sql declares %d: the DDL is judged and generated by %d's rules; declare `-- sqlshape: postgres %d` if the database is the one meant", server, int(declared.Or()), int(declared.Or()), major)
}
