package analyze

import (
	"context"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/kr9ly/sqlshape/check/postgres/v2/oracle"
)

// TestNestedRowFieldsFollowColumnNullability is docs/checks.md's own "Nested rows are
// received by structs" Passes example (SELECT o.id, array_agg((i.sku, i.qty)::order_item)
// ... FROM orders o JOIN order_items i ...): order_item's sku/qty columns are declared
// NOT NULL in order_items, and the row-constructor cast that builds each array element
// keeps that -- (i.sku, i.qty)::order_item is coerce_record_to_complex applied to a
// RowExpr whose own fields already carry the source columns' nullability (analyzeExpr's
// Node_RowExpr case), so the cast's per-field nullable does not fall back to the
// composite type's own declared columns (a free-standing CREATE TYPE has no NOT NULL of
// its own to ask -- rowFields in dialect/types.go always answers false).
func TestNestedRowFieldsFollowColumnNullability(t *testing.T) {
	schemaSQL := `
CREATE TABLE orders (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);
CREATE TABLE order_items (
    order_id bigint NOT NULL REFERENCES orders(id),
    sku      text NOT NULL,
    qty      integer NOT NULL
);
CREATE TYPE order_item AS (sku text, qty integer);
`
	s, err := Load(schemaSQL)
	if err != nil {
		t.Fatal(err)
	}
	sql := `SELECT o.id, array_agg((i.sku, i.qty)::order_item) AS items
  FROM orders o JOIN order_items i ON i.order_id = o.id
 GROUP BY o.id`
	r, aerr := Analyze(s, sql)
	if aerr != nil {
		t.Fatalf("analyze: %v", aerr)
	}
	items := r.Columns[1]
	if items.Name != "items" || len(items.Fields) != 2 {
		t.Fatalf("unexpected items column: %+v", items)
	}
	for _, f := range items.Fields {
		if f.Nullable {
			t.Errorf("field %s: nullable, want not-null (order_items.%s is NOT NULL and (i.sku, i.qty)::order_item does not lose that)", f.Name, f.Name)
		}
	}
	// array_agg's own argument here is (i.sku, i.qty)::order_item: a row constructor,
	// never NULL itself regardless of its fields' own nullability -- see
	// TestNestedRowConstructorNeverNullButArrayAggPassesScalarNullsThrough below for the
	// measured PostgreSQL fact this relies on. items.ElemNotNull lets the contract (and so
	// the checker's -strict rejection / standing note) say so.
	if !items.ElemNotNull {
		t.Errorf("items: ElemNotNull = false, want true (array_agg's argument is a row constructor, never NULL itself)")
	}
}

// TestNestedRowConstructorNeverNullButArrayAggPassesScalarNullsThrough measures two real
// PostgreSQL facts docs/checks.md's "Nested rows" Passes example relies on, against a
// running server (not just the parser's own rules):
//
//  1. array_agg() passes an argument's own NULL straight into the array as a NULL
//     element ({1,NULL,3}), whatever the source column's own nullability.
//  2. A row constructor -- row(...) or (a, b) -- is itself never NULL, even when every
//     field composing it is (a LEFT JOIN's unmatched side has i.sku, i.qty both NULL,
//     yet (i.sku, i.qty) comes back as a row of two NULL fields, ("",NULL) in the text
//     format's row-with-a-null-field spelling, not a bare NULL array element).
//
// So array_agg(scalar) and array_agg(row(...)) are not the same hazard: the first can
// really put a NULL element in the array (vet's blanket "may contain a NULL element"
// note is earning its keep there); the second cannot, by construction -- the note is a
// false positive for it. dialect.Type.ElemNotNull (see rteCol.elemNotNull / expr.elemNotNull
// in this package, and TestArrayElemNotNull below) threads that fact through the
// dialect-neutral contract so cmd/sqlshape/internal/vet/gofit.go's addArrayNullElemNotes
// gate can skip the note for this shape while still giving it for array_agg(scalar).
func TestNestedRowConstructorNeverNullButArrayAggPassesScalarNullsThrough(t *testing.T) {
	schemaSQL := `
CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
CREATE TABLE order_items (
    order_id bigint NOT NULL REFERENCES orders(id),
    sku      text,
    qty      integer
);
`
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	o, err := oracle.Start(ctx, schemaSQL)
	if err != nil {
		t.Fatalf("oracle start: %v", err)
	}
	defer o.Close()
	conn := o.Conn()

	if _, err := conn.Exec(ctx, `INSERT INTO orders (id) VALUES (1)`); err != nil {
		t.Fatalf("insert orders: %v", err)
	}
	if _, err := conn.Exec(ctx, `INSERT INTO order_items (order_id, sku, qty) VALUES (1, 'a', 1), (1, NULL, NULL)`); err != nil {
		t.Fatalf("insert order_items: %v", err)
	}

	var scalarArrayText string
	if err := conn.QueryRow(ctx, `SELECT array_agg(qty)::text FROM order_items WHERE order_id = 1`).Scan(&scalarArrayText); err != nil {
		t.Fatalf("scalar array_agg: %v", err)
	}
	if !strings.Contains(scalarArrayText, "NULL") {
		t.Errorf("array_agg(qty) = %s: want a bare NULL element (qty has a NULL row)", scalarArrayText)
	}

	var rowArrayText string
	if err := conn.QueryRow(ctx, `SELECT array_agg((sku, qty))::text FROM order_items WHERE order_id = 1`).Scan(&rowArrayText); err != nil {
		t.Fatalf("row array_agg: %v", err)
	}
	// want exactly {"(a,1)","(,)"}: two elements, each parenthesized -- the second row's
	// NULL sku/qty show up as an empty field ",", never as a bare, unparenthesized NULL
	// array element the way array_agg(qty) alone produced one above.
	const want = `{"(a,1)","(,)"}`
	if rowArrayText != want {
		t.Errorf("array_agg((sku, qty)) = %s, want %s (a row constructor is never itself NULL, even with all-NULL fields)", rowArrayText, want)
	}
	if strings.Contains(rowArrayText, "NULL") {
		t.Errorf("array_agg((sku, qty)) = %s: contains a bare NULL, but a row constructor should never itself be NULL", rowArrayText)
	}
}

// TestArrayElemNotNull covers dialect.Type.ElemNotNull's every source against the shared
// testdata/schema.sql: array_agg() of a value known not-null vs. one that is not, a
// literal ARRAY[...], ARRAY(SELECT ...), a set operation over two arms, and the default
// (false, "unknown") for a plain array column.
func TestArrayElemNotNull(t *testing.T) {
	schemaSQL, err := os.ReadFile("testdata/schema.sql")
	if err != nil {
		t.Fatal(err)
	}
	s, err := Load(string(schemaSQL))
	if err != nil {
		t.Fatal(err)
	}
	cases := []struct {
		name string
		sql  string
		want bool
	}{
		{"array_agg of a NOT NULL column", "SELECT array_agg(id) FROM orders", true},
		{"array_agg of a nullable column", "SELECT array_agg(note) FROM orders", false},
		{"array_agg of a row constructor", "SELECT array_agg(row(id, total)) FROM orders", true},
		{"array_agg of a whole-row reference", "SELECT array_agg(o) FROM orders o", true},
		{"a plain array column", "SELECT matrix FROM orders", false},
		{"ARRAY[...] with every element not null", "SELECT ARRAY[1, 2, 3]", true},
		{"ARRAY[...] with a NULL element", "SELECT ARRAY[1, NULL, 3]", false},
		{"ARRAY(SELECT ...) over a NOT NULL column", "SELECT ARRAY(SELECT id FROM orders)", true},
		{"ARRAY(SELECT ...) over a nullable column", "SELECT ARRAY(SELECT note FROM orders)", false},
		{"UNION of two proven arms", "SELECT ARRAY[1, 2] UNION SELECT ARRAY[3, 4]", true},
		{"UNION where one arm is not proven", "SELECT ARRAY[1, 2] UNION SELECT ARRAY[NULL, 4]", false},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			r, aerr := Analyze(s, c.sql)
			if aerr != nil {
				t.Fatalf("analyze %q: %v", c.sql, aerr)
			}
			if got := r.Columns[0].ElemNotNull; got != c.want {
				t.Errorf("%s:\n  %s\nElemNotNull = %v, want %v", c.name, c.sql, got, c.want)
			}
		})
	}
}

// TestArrayElemNotNullThroughFrozenView: a view whose defining query proves its array
// column's elements never NULL keeps the proof in its frozen column snapshot, so a query
// over the view (the frozen path, not a fresh analysis of the body) reports ElemNotNull.
func TestArrayElemNotNullThroughFrozenView(t *testing.T) {
	s, err := Load(`
CREATE TABLE rooms (id bigint PRIMARY KEY, name text NOT NULL);
CREATE TABLE bookings (id bigint PRIMARY KEY, room_id bigint NOT NULL REFERENCES rooms (id), note text);
CREATE TYPE slot AS (id bigint, note text);
CREATE VIEW room_schedule AS
SELECT r.id AS room_id, array_agg(row(b.id, b.note)::slot) FILTER (WHERE b.id IS NOT NULL) AS bookings, array_agg(b.note) AS notes
  FROM rooms r LEFT JOIN bookings b ON b.room_id = r.id GROUP BY r.id;
`)
	if err != nil {
		t.Fatal(err)
	}
	r, err := Analyze(s, "SELECT room_id, bookings, notes FROM room_schedule")
	if err != nil {
		t.Fatal(err)
	}
	if !r.Columns[1].ElemNotNull {
		t.Error("bookings: array_agg of a row constructor through the view must keep ElemNotNull")
	}
	if r.Columns[2].ElemNotNull {
		t.Error("notes: array_agg of a nullable column must not claim ElemNotNull")
	}
}
