package analyze

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/kr9ly/sqlshape/check/mysql/v2/internal/oracle"
	"github.com/kr9ly/sqlshape/check/mysql/v2/internal/schema"
)

// fullGroupSchema adds to the test schema a table with a nullable UNIQUE key and nullable
// non-key columns, which the functional dependencies turn on.
const fullGroupSchema = testSchema + `
CREATE TABLE t1 (
  pk INT NOT NULL PRIMARY KEY,
  a INT NOT NULL,
  b INT,
  u INT,
  c INT,
  UNIQUE KEY (u)
);
`

// fullGroupCases are statements a real mysqld (8.4, sql_mode ONLY_FULL_GROUP_BY) accepts
// (0) or rejects with the error number given: the group-invariance check, the HAVING
// resolution rule, DISTINCT with ORDER BY, aggregates in ORDER BY. TestFullGroupOracle
// keeps them the server's verdicts. Not here: a parenthesized join in a join (the analyzer
// does not read PT_table_factor_joined_table yet) and an expression in the ORDER BY of a set
// operation.
var fullGroupCases = []struct {
	sql  string
	code int
}{
	{"SELECT name, COUNT(*) FROM users GROUP BY id", 0},
	{"SELECT u.name, o.total FROM users u JOIN orders o ON o.user_id = u.id GROUP BY o.id", 0},
	{"SELECT name FROM users WHERE id = 1 GROUP BY email", 0},
	{"SELECT name, COUNT(*) FROM users WHERE id = 1", 0},
	{"SELECT u.name, o.total FROM users u LEFT JOIN orders o ON o.user_id = u.id GROUP BY o.id", 1055},
	{"SELECT u.name, o.total FROM users u LEFT JOIN orders o ON o.id = u.id GROUP BY u.id", 0},
	{"SELECT YEAR(created_at), COUNT(*) FROM users GROUP BY YEAR(created_at)", 0},
	{"SELECT YEAR(created_at) + 1 FROM users GROUP BY YEAR(created_at)", 1055},
	{"SELECT id + 1 AS x, COUNT(*) FROM users GROUP BY x", 0},
	{"SELECT name, COUNT(*) FROM users GROUP BY 1", 0},
	{"SELECT id, COUNT(*) FROM users GROUP BY id WITH ROLLUP", 0},
	{"SELECT name FROM users GROUP BY id WITH ROLLUP", 1055},
	{"SELECT d.n, d.c FROM (SELECT name n, COUNT(*) c FROM users GROUP BY name) d GROUP BY d.n", 0},
	{"SELECT d.name, d.email FROM (SELECT id, name, email FROM users) d GROUP BY d.id", 0},
	{"SELECT d.name FROM (SELECT id, name FROM users LIMIT 5) d GROUP BY d.id", 0},
	{"SELECT email, COUNT(*) FROM users GROUP BY name", 1055},
	{"SELECT name, COUNT(*) FROM users", 1140},
	{"SELECT name FROM users GROUP BY name HAVING email = 'x'", 1054},
	{"SELECT name FROM users GROUP BY name ORDER BY email", 1055},
	{"SELECT name AS n FROM users GROUP BY name HAVING n = 'x'", 0},
	{"SELECT (SELECT COUNT(*) FROM orders o WHERE o.user_id = u.id) FROM users u GROUP BY u.name", 1055},
	{"SELECT (SELECT COUNT(*) FROM orders o WHERE o.user_id = u.id) FROM users u GROUP BY u.id", 0},
	{"SELECT * FROM users GROUP BY id", 0},
	{"SELECT *, COUNT(*) FROM orders GROUP BY user_id", 1055},
	{"SELECT c FROM t1 GROUP BY u", 1055},
	{"SELECT c FROM t1 WHERE u IS NOT NULL GROUP BY u", 0},
	{"SELECT c FROM t1 WHERE u > 1 GROUP BY u", 0},
	{"SELECT c FROM t1 WHERE u = 1 GROUP BY a", 0},
	{"SELECT c FROM t1 GROUP BY b", 1055},
	{"SELECT COUNT(*) FROM users ORDER BY name", 0},
	{"SELECT name FROM users ORDER BY COUNT(*)", 3029},
	{"SELECT DISTINCT name FROM users ORDER BY email", 3065},
	{"SELECT DISTINCT name FROM users ORDER BY id", 3065},
	{"SELECT DISTINCT name, id FROM users ORDER BY id + 1", 0},
	{"SELECT DISTINCT name FROM users ORDER BY COUNT(*)", 3029},
	{"SELECT DISTINCT name FROM users GROUP BY name ORDER BY email", 1055},
	{"SELECT u.name FROM users u JOIN orders o USING (id) GROUP BY o.id", 0},
	{"SELECT u.name, o.total FROM users u JOIN orders o ON o.user_id = u.id WHERE o.id = 5 GROUP BY u.email", 0},
	{"SELECT name, COUNT(*) FROM users GROUP BY id HAVING COUNT(*) > 1", 0},
	{"SELECT name, ROW_NUMBER() OVER (ORDER BY email) FROM users GROUP BY id", 0},
	{"SELECT name, ROW_NUMBER() OVER (ORDER BY email) FROM users GROUP BY name", 1055},
	{"SELECT name, ROW_NUMBER() OVER w FROM users GROUP BY name WINDOW w AS (ORDER BY email)", 1055},
	{"SELECT n FROM v_stats GROUP BY user_id", 0},
	{"SELECT v.name FROM v_users v GROUP BY v.id", 0},
	{"SELECT email FROM users WHERE name = email GROUP BY name", 0},
	{"SELECT (SELECT name FROM users WHERE id = o.user_id) FROM orders o GROUP BY o.id", 0},
	{"SELECT name, COUNT(*) FROM users WHERE name = 'x'", 0},
	{"SELECT UPPER(CONCAT(name, email)) FROM users GROUP BY CONCAT(name, email)", 1055},
	{"SELECT id AS name, COUNT(*) FROM users GROUP BY name", 1055},
	{"SELECT o.total FROM orders o JOIN users u ON u.id = o.user_id GROUP BY u.id", 1055},
	{"SELECT o.total FROM users u LEFT JOIN orders o ON o.id = 5 GROUP BY u.id", 0},
	{"SELECT d.name FROM (SELECT * FROM users WHERE id = 1) d GROUP BY d.email", 0},
	{"SELECT d.name FROM (SELECT * FROM users WHERE id = 1 LIMIT 1) d GROUP BY d.email", 0},
	{"SELECT d.name FROM (SELECT * FROM users LIMIT 1) d GROUP BY d.email", 1055},
	{"SELECT t1.c FROM t1 GROUP BY t1.b", 1055},
	{"SELECT a, b FROM t1 GROUP BY a + b", 1055},
	{"SELECT a + b FROM t1 GROUP BY b + a", 1055},
	{"SELECT a FROM t1 GROUP BY A", 0},
	{"SELECT 'x', a FROM t1 GROUP BY 'x'", 1055},
	{"SELECT c FROM t1 WHERE (u, a) = (1, 2) GROUP BY b", 0},
	{"SELECT c FROM t1 WHERE u = a GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = a + 1 GROUP BY a", 1055},
	{"SELECT c FROM t1 WHERE u = ABS(a) GROUP BY a", 1055},
	{"SELECT c FROM t1 x JOIN t1 y ON x.u = y.a GROUP BY y.a", 1052},
	{"SELECT x.c FROM t1 x LEFT JOIN t1 y ON x.u = y.pk GROUP BY y.pk", 1055},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.u = x.a GROUP BY x.a", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.b = x.a GROUP BY x.a", 1055},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.u = x.a AND y.c > 0 GROUP BY x.a", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.u = x.a OR y.b = 1 GROUP BY x.a", 1055},
	{"SELECT c FROM t1 GROUP BY u HAVING u IS NOT NULL", 1055},
	{"SELECT c FROM t1 WHERE u IN (1, 2) GROUP BY u", 0},
	{"SELECT MAX(c) FROM t1 GROUP BY a ORDER BY b", 1055},
	{"SELECT a FROM t1 GROUP BY a ORDER BY MAX(c)", 0},
	{"SELECT a FROM t1 GROUP BY a ORDER BY b + 0", 1055},
	{"SELECT a, b FROM t1 GROUP BY a, b ORDER BY 2", 0},
	{"SELECT a FROM t1 GROUP BY a HAVING b > 0", 1054},
	{"SELECT a FROM t1 GROUP BY a HAVING MAX(b) > 0 AND b > 0", 1054},
	{"SELECT id FROM users UNION SELECT id FROM users GROUP BY name", 1055},
	{"SELECT d.b FROM (SELECT a, b FROM t1 GROUP BY a) d", 1055},
	{"SELECT d.b FROM (SELECT a, MAX(b) b FROM t1 GROUP BY a) d GROUP BY d.a", 0},
	{"SELECT d.b FROM (SELECT a, MAX(b) b FROM t1 GROUP BY a) d GROUP BY d.a + 1", 1055},
	{"SELECT d.s FROM (SELECT b*3 AS c, SUM(a) AS s FROM t1 GROUP BY b*3) AS d GROUP BY d.c", 0},
	{"SELECT d.b FROM (SELECT a, b FROM t1 UNION SELECT a, b FROM t1) d GROUP BY d.a", 1055},
	{"SELECT d.c FROM (SELECT pk, c FROM t1 UNION ALL SELECT pk, c FROM t1) d GROUP BY d.pk", 1055},
	{"WITH w AS (SELECT pk, c FROM t1) SELECT w.c FROM w GROUP BY w.pk", 0},
	{"WITH w AS (SELECT a, c FROM t1) SELECT w.c FROM w GROUP BY w.a", 1055},
	{"SELECT x.c FROM t1 x LEFT JOIN (SELECT pk, c FROM t1) d ON d.pk = x.a GROUP BY x.pk", 0},
	{"SELECT d.c FROM t1 x LEFT JOIN (SELECT pk, c FROM t1) d ON d.pk = x.a GROUP BY x.pk", 0},
	{"SELECT d.c FROM t1 x LEFT JOIN (SELECT pk, c FROM t1 LIMIT 3) d ON d.pk = x.a GROUP BY x.pk", 0},
	{"SELECT d.c FROM t1 x LEFT JOIN (SELECT a, MAX(c) c FROM t1 GROUP BY a) d ON d.a = x.a GROUP BY x.a", 0},
	{"SELECT d.c FROM t1 x LEFT JOIN (SELECT a, MAX(c) c FROM t1 GROUP BY a) d ON d.a = x.b GROUP BY x.b", 0},
	{"SELECT c FROM t1 WHERE pk = (SELECT MAX(pk) FROM t1) GROUP BY b", 1055},
	{"SELECT c FROM t1 WHERE pk = $1 GROUP BY b", 1055},
	{"SELECT c FROM t1 WHERE pk = RAND() GROUP BY b", 1055},
	{"SELECT c FROM t1 WHERE pk = @v GROUP BY b", 1055},
	{"SELECT c, COUNT(*) FROM t1 GROUP BY a WITH ROLLUP HAVING c > 0", 1055},
	{"SELECT a, COUNT(*) FROM t1 GROUP BY a WITH ROLLUP ORDER BY b", 1055},
	{"SELECT a, GROUPING(a) FROM t1 GROUP BY a WITH ROLLUP", 0},
	{"SELECT ANY_VALUE(c) FROM t1 GROUP BY a", 0},
	{"SELECT c FROM t1 GROUP BY a, u HAVING u = 1", 1055},
	{"SELECT (SELECT x.c FROM t1 x WHERE x.pk = y.a) FROM t1 y GROUP BY y.b", 1055},
	{"SELECT (SELECT COUNT(*) FROM t1 x WHERE x.c = c) FROM t1 y GROUP BY y.b", 0},
	{"SELECT (SELECT COUNT(*) FROM t1 x WHERE x.c = y.c) FROM t1 y GROUP BY y.b", 1055},
	{"SELECT (SELECT MAX(y.c) FROM t1 x) FROM t1 y GROUP BY y.b", 0},
	{"SELECT EXISTS (SELECT 1 FROM t1 x WHERE x.c = y.c) FROM t1 y GROUP BY y.b", 1055},
	{"SELECT y.c IN (SELECT x.a FROM t1 x) FROM t1 y GROUP BY y.b", 1055},
	{"SELECT COUNT(*), COUNT(*) OVER () FROM t1", 0},
	{"SELECT a, COUNT(*) OVER (PARTITION BY c) FROM t1 GROUP BY a", 1055},
	{"SELECT SUM(a) OVER (PARTITION BY c) FROM t1 GROUP BY a", 1055},
	{"SELECT a FROM t1 GROUP BY a WINDOW w AS (PARTITION BY c)", 1055},
	{"SELECT CASE WHEN a > 0 THEN c ELSE 0 END FROM t1 GROUP BY a", 1055},
	{"SELECT IF(a > 0, c, 0) FROM t1 GROUP BY a, c", 0},
	{"SELECT COUNT(DISTINCT c), a FROM t1 GROUP BY a", 0},
	{"SELECT a, MAX(c) FROM t1 GROUP BY a, a", 0},
	{"SELECT a, c FROM t1 GROUP BY pk, a", 0},
	{"SELECT a FROM t1 GROUP BY 1 + 1", 1055},
	{"SELECT a, COUNT(*) FROM t1 GROUP BY NULL", 1055},
	{"SELECT c FROM t1 WHERE a = 1 AND b = a GROUP BY pk", 0},
	{"SELECT t1.c, u2.name FROM t1, users u2 WHERE t1.pk = 1 GROUP BY u2.id", 0},
	{"SELECT t1.c, u2.name FROM t1, users u2 WHERE t1.pk = u2.id GROUP BY u2.id", 0},
	{"SELECT t1.c, u2.name FROM t1, users u2 WHERE t1.a = u2.id GROUP BY u2.id", 1055},
	{"SELECT t1.c, u2.name FROM t1, users u2 WHERE t1.u = u2.id GROUP BY u2.id", 0},
	{"SELECT name FROM users u GROUP BY u.secret", 1055},
	{"SELECT DISTINCT a FROM t1 ORDER BY a + b", 3065},
	{"SELECT DISTINCT a + 1 AS x FROM t1 ORDER BY x", 0},
	{"SELECT DISTINCT a + 1 FROM t1 ORDER BY a + 1", 0},
	{"SELECT DISTINCT a FROM t1 ORDER BY (SELECT b FROM t1 x WHERE x.pk = t1.a)", 0},
	{"SELECT DISTINCT a FROM t1 ORDER BY (SELECT MAX(b) FROM t1 x)", 0},
	{"SELECT DISTINCT a FROM t1 ORDER BY RAND()", 0},
	{"SELECT DISTINCT a FROM t1 ORDER BY 1", 0},
	{"SELECT DISTINCT a FROM t1 ORDER BY 2", 1054},
	{"SELECT DISTINCT t1.* FROM t1 ORDER BY b", 0},
	{"SELECT DISTINCT a FROM t1 x JOIN t1 y USING (pk) ORDER BY y.b", 1052},
	{"SELECT DISTINCT * FROM t1 ORDER BY b", 0},
	{"SELECT DISTINCT a FROM t1 GROUP BY a ORDER BY MAX(b)", 0},
	{"SELECT DISTINCT a FROM t1 GROUP BY a, b ORDER BY b", 3065},
	{"SELECT DISTINCT a, ROW_NUMBER() OVER (ORDER BY b) FROM t1 ORDER BY b", 3065},
	{"SELECT DISTINCT a FROM t1 ORDER BY ROW_NUMBER() OVER (ORDER BY b)", 0},
	{"SELECT a FROM t1 UNION SELECT a FROM t1 ORDER BY MAX(a)", 3028},
	{"(SELECT a FROM t1 ORDER BY b) UNION (SELECT a FROM t1)", 0},
	{"SELECT a FROM t1 GROUP BY a ORDER BY (SELECT MAX(x.b) FROM t1 x WHERE x.pk = t1.b)", 1055},
	{"SELECT a FROM t1 GROUP BY a ORDER BY (SELECT MAX(x.b) FROM t1 x WHERE x.pk = t1.a)", 0},
	{"UPDATE t1 SET c = 1 WHERE pk IN (SELECT pk FROM (SELECT pk, c FROM t1 GROUP BY a) d)", 1055},
	{"INSERT INTO t1 (pk, a) SELECT pk, c FROM t1 GROUP BY a", 1055},
	{"SELECT a FROM t1 GROUP BY a HAVING (SELECT c FROM t1 x WHERE x.pk = t1.b) > 0", 1054},
	{"SELECT a FROM t1 GROUP BY a HAVING (SELECT c FROM t1 x WHERE x.pk = t1.a) > 0", 0},
	{"SELECT a FROM t1 GROUP BY a HAVING a > 0 OR c > 0", 1054},
	{"SELECT a FROM t1 GROUP BY a HAVING MAX(c) > 0 AND (SELECT MAX(b) FROM t1 x) > 0", 0},
	{"SELECT a, MAX(c) m FROM t1 GROUP BY a HAVING m > 0 ORDER BY m", 0},
	{"SELECT a, MAX(c) FROM t1 GROUP BY a ORDER BY MAX(c) DESC", 0},
	{"SELECT a FROM t1 GROUP BY a ORDER BY a, MIN(b), 1", 0},
	{"SELECT a FROM t1 GROUP BY a ORDER BY a + b", 1055},
	{"SELECT a b FROM t1 GROUP BY a ORDER BY b", 0},
	{"SELECT a b FROM t1 GROUP BY b", 1055},
	{"SELECT a, MAX(c) FROM t1 GROUP BY a ORDER BY NULL", 0},
	{"SELECT a, MAX(c) FROM t1 GROUP BY a ORDER BY RAND()", 0},
	{"SELECT a FROM t1 GROUP BY a ORDER BY (SELECT 1)", 0},
	{"SELECT a, COUNT(*) FROM t1 GROUP BY a ORDER BY c LIMIT 1", 1055},
	{"SELECT COUNT(*) FROM t1 HAVING a > 0", 1054},
	{"SELECT COUNT(*) FROM t1 HAVING MAX(a) > 0", 0},
	{"SELECT a FROM t1 HAVING a > 0", 0},
	{"SELECT a FROM t1 HAVING MAX(a) > 0", 1140},
	{"SELECT a FROM t1 HAVING COUNT(*) > 0", 1140},
	{"SELECT a, ROW_NUMBER() OVER () FROM t1 HAVING a > 0", 0},
	{"SELECT 1 FROM t1 GROUP BY a ORDER BY b", 1055},
	{"SELECT a FROM t1 GROUP BY a ORDER BY t1.b", 1055},
	{"SELECT * FROM t1 GROUP BY a", 1055},
	{"SELECT t1.*, MAX(c) FROM t1 GROUP BY pk", 0},
	{"SELECT x.* FROM t1 x JOIN t1 y ON x.a = y.pk GROUP BY y.pk", 1055},
	{"SELECT x.* FROM t1 x LEFT JOIN t1 y ON x.a = y.pk GROUP BY y.pk", 1055},
	{"SELECT x.*, y.a FROM t1 x LEFT JOIN t1 y ON y.a = x.pk GROUP BY x.pk", 0},
	{"SELECT x.*, y.c FROM t1 x LEFT JOIN t1 y ON y.u = x.pk GROUP BY x.pk", 0},
	{"SELECT x.*, y.c FROM t1 x RIGHT JOIN t1 y ON y.u = x.pk GROUP BY y.pk", 0},
	{"SELECT x.*, y.c FROM t1 x RIGHT JOIN t1 y ON y.u = x.pk GROUP BY x.pk", 1055},
	{"SELECT x.c FROM t1 x JOIN t1 y ON x.u = y.pk WHERE y.pk = 3 GROUP BY y.b", 0},
	{"SELECT x.c FROM t1 x LEFT JOIN t1 y ON x.u = y.pk WHERE y.pk = 3 GROUP BY y.b", 0},
	{"SELECT x.c FROM t1 x LEFT JOIN t1 y ON x.u = y.pk AND y.b = 3 GROUP BY x.pk", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON x.u = y.pk AND y.b = 3 GROUP BY x.pk", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.pk = 3 GROUP BY x.pk", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.u = 3 GROUP BY x.pk", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.pk = x.b GROUP BY x.pk", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.pk = x.b GROUP BY x.b", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.pk = COALESCE(x.b, 0) GROUP BY x.b", 1055},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.pk = x.b + x.a GROUP BY x.b", 1055},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.pk = x.b + x.a GROUP BY x.b, x.a", 1055},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.u = x.b GROUP BY x.b", 0},
	{"SELECT y.c FROM t1 x JOIN t1 y ON y.u = x.b GROUP BY x.b", 0},
	{"SELECT y.c FROM t1 x JOIN t1 y ON y.u = x.b WHERE x.b IS NOT NULL GROUP BY x.b", 0},
	{"SELECT y.c FROM t1 x JOIN t1 y ON y.u = x.b WHERE y.u IS NOT NULL GROUP BY x.b", 0},
	{"SELECT y.c FROM t1 x JOIN t1 y ON y.u = x.b WHERE y.u > 0 GROUP BY x.b", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.u = x.b WHERE y.u IS NOT NULL GROUP BY x.b", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON x.a = y.u GROUP BY x.a", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.u = x.pk GROUP BY x.pk", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.u = x.pk WHERE y.pk IS NOT NULL GROUP BY x.pk", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.u = x.pk AND y.c IS NOT NULL GROUP BY x.pk", 0},
	{"SELECT c FROM t1 WHERE u = 1 OR u = 2 GROUP BY u", 1055},
	{"SELECT c FROM t1 WHERE u <=> 1 GROUP BY u", 1055},
	{"SELECT c FROM t1 WHERE NOT u = 1 GROUP BY u", 0},
	{"SELECT c FROM t1 WHERE u LIKE '1' GROUP BY u", 0},
	{"SELECT c FROM t1 WHERE u BETWEEN 1 AND 2 GROUP BY u", 0},
	{"SELECT c FROM t1 WHERE u + 1 = 2 GROUP BY u", 1055},
	{"SELECT c FROM t1 WHERE COALESCE(u, 0) = 2 GROUP BY u", 1055},
	{"SELECT c FROM t1 WHERE u IS NULL GROUP BY u", 1055},
	{"SELECT c FROM t1 WHERE u IS NULL GROUP BY a", 1055},
	{"SELECT c FROM t1 WHERE u = NULL GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = b GROUP BY u", 0},
	{"SELECT c FROM t1 WHERE u = b GROUP BY b", 0},
	{"SELECT c FROM t1 WHERE u = a GROUP BY b", 1055},
	{"SELECT c FROM t1 WHERE pk = a GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE pk = a GROUP BY b", 1055},
	{"SELECT c FROM t1 WHERE a = 1 GROUP BY a", 1055},
	{"SELECT c FROM t1 WHERE a = 1 AND b = 2 GROUP BY u", 1055},
	{"SELECT a, c FROM t1 WHERE a = 1 AND b = 2 GROUP BY u", 1055},
	{"SELECT c FROM t1 GROUP BY a HAVING a = 1", 1055},
	{"SELECT COUNT(*), c FROM t1 WHERE a = 1 AND pk = 2", 0},
	{"SELECT COUNT(*), c FROM t1 WHERE pk = 2", 0},
	{"SELECT COUNT(*), c FROM t1 WHERE pk = 2 OR pk = 3", 1140},
	{"SELECT COUNT(*), c FROM t1 WHERE u = 2", 0},
	{"SELECT COUNT(*), c FROM t1 WHERE u <=> 2", 1140},
	{"SELECT COUNT(*), c FROM t1 WHERE u <=> NULL", 1140},
	{"SELECT a FROM t1 HAVING b > 0", 1054},
	{"SELECT a FROM t1 HAVING MAX(b) > 0 AND a > 0", 1140},
	{"SELECT a FROM t1 GROUP BY a HAVING t1.a > 0", 0},
	{"SELECT a FROM t1 GROUP BY a HAVING pk > 0", 1054},
	{"SELECT a FROM t1 GROUP BY a, u HAVING u > 0", 0},
	{"SELECT a FROM t1 GROUP BY a HAVING (SELECT MAX(x.c) FROM t1 x WHERE x.pk = t1.pk) > 0", 1054},
	{"SELECT a FROM t1 GROUP BY a HAVING EXISTS (SELECT 1 FROM t1 x WHERE x.b = t1.c)", 1054},
	{"SELECT a AS z FROM t1 GROUP BY a HAVING z > 0 AND a > 0", 0},
	{"SELECT a + 1 AS z FROM t1 GROUP BY a HAVING a > 0", 0},
	{"SELECT a + 1 AS z FROM t1 GROUP BY z HAVING a > 0", 1054},
	{"SELECT a FROM t1 GROUP BY a HAVING a + b > 0", 1054},
	{"SELECT a FROM t1 GROUP BY a HAVING SUM(b) > 0 AND MAX(t1.c) > 0", 0},
	{"SELECT x.d FROM (SELECT pk, c + 1 AS d FROM t1) x GROUP BY x.pk", 0},
	{"SELECT x.d FROM (SELECT pk, c + 1 AS d FROM t1 LIMIT 3) x GROUP BY x.pk", 0},
	{"SELECT x.d FROM (SELECT pk, RAND() AS d FROM t1) x GROUP BY x.pk", 0},
	{"SELECT x.d FROM (SELECT b, MAX(c) AS d FROM t1 GROUP BY b) x GROUP BY x.b", 0},
	{"SELECT x.d FROM (SELECT b, MAX(c) AS d FROM t1 GROUP BY b) x GROUP BY x.d", 0},
	{"SELECT x.d, x.e FROM (SELECT b, MAX(c) AS d, MIN(c) AS e FROM t1 GROUP BY b) x GROUP BY x.d", 1055},
	{"SELECT x.b FROM (SELECT b, MAX(c) AS d FROM t1 GROUP BY b) x GROUP BY x.d", 1055},
	{"SELECT x.e FROM (SELECT a, b, MAX(c) AS e FROM t1 GROUP BY a, b) x GROUP BY x.a", 1055},
	{"SELECT x.e FROM (SELECT a, b, MAX(c) AS e FROM t1 GROUP BY a, b) x WHERE x.b = 1 GROUP BY x.a", 0},
	{"SELECT x.e FROM (SELECT a, b, MAX(c) AS e FROM t1 GROUP BY a, b) x WHERE x.b = 1 LIMIT 1", 0},
	{"SELECT x.c FROM (SELECT pk, c FROM t1 WHERE u = 5) x GROUP BY x.a", 1054},
	{"SELECT x.c FROM (SELECT pk, c, a FROM t1 WHERE u = 5) x GROUP BY x.a", 0},
	{"SELECT x.c FROM (SELECT pk, c, a FROM t1 WHERE u = 5 LIMIT 2) x GROUP BY x.a", 0},
	{"SELECT x.c FROM (SELECT pk, c, a FROM t1 WHERE pk = 5 LIMIT 2) x GROUP BY x.a", 0},
	{"SELECT x.c FROM (SELECT pk, c, a FROM t1 WHERE u = 5 LIMIT 2) x GROUP BY x.pk", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN (SELECT b, c FROM t1) y ON y.b = x.a GROUP BY x.a", 1055},
	{"SELECT y.c FROM t1 x LEFT JOIN (SELECT b, c FROM t1 LIMIT 5) y ON y.b = x.a GROUP BY x.a", 1055},
	{"SELECT y.c FROM t1 x LEFT JOIN (SELECT u, c FROM t1) y ON y.u = x.a GROUP BY x.a", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN (SELECT u, c FROM t1 LIMIT 5) y ON y.u = x.a GROUP BY x.a", 1055},
	{"SELECT y.c FROM t1 x LEFT JOIN (SELECT b, MAX(c) c FROM t1 GROUP BY b) y ON y.b = x.a GROUP BY x.a", 1055},
	{"SELECT y.c FROM t1 x LEFT JOIN (SELECT b, MAX(c) c FROM t1 GROUP BY b) y ON y.b = x.b GROUP BY x.b", 1055},
	{"SELECT y.c FROM t1 x LEFT JOIN (SELECT a, b, MAX(c) c FROM t1 GROUP BY a, b) y ON y.b = x.b AND y.a = x.a GROUP BY x.b, x.a", 0},
	{"SELECT y.d FROM t1 x LEFT JOIN (SELECT pk, c + 1 AS d FROM t1) y ON y.pk = x.a GROUP BY x.a", 0},
	{"SELECT y.d FROM t1 x LEFT JOIN (SELECT pk, COALESCE(c, 0) AS d FROM t1) y ON y.pk = x.a GROUP BY x.a", 0},
	{"SELECT y.d FROM t1 x LEFT JOIN (SELECT pk, COALESCE(c, 0) AS d FROM t1 LIMIT 5) y ON y.pk = x.a GROUP BY x.a", 0},
	{"SELECT y.d FROM t1 x JOIN (SELECT pk, COALESCE(c, 0) AS d FROM t1) y ON y.pk = x.a GROUP BY x.a", 0},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.pk = x.a AND RAND() > 0.5 GROUP BY x.a", 1055},
	{"SELECT y.c FROM t1 x LEFT JOIN t1 y ON y.pk = x.a AND (SELECT MAX(b) FROM t1) > 0 GROUP BY x.a", 0},
	{"SELECT c FROM t1 WHERE u = 1 + 1 GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = ABS(-1) GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = NOW() GROUP BY a", 1055},
	{"SELECT c FROM t1 WHERE u = CURRENT_DATE GROUP BY a", 1055},
	{"SELECT c FROM t1 WHERE u = @@version GROUP BY a", 1055},
	{"SELECT c FROM t1 WHERE u = (SELECT 1) GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = CAST('1' AS SIGNED) GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = _utf8mb4'1' GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = -1 GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = DATE '2020-01-01' GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = TRUE GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = 0x01 GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = b'1' GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = 1.5 GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = 1e1 GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = 'x' 'y' GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE 1 = u GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE (u) = 1 GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = 1 AND 1 = 1 GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE u = 1 AND (a = 1 AND b = 2) GROUP BY a", 0},
	{"SELECT c FROM t1 WHERE (u = 1 OR u = 1) GROUP BY a", 1055},
	{"SELECT c FROM t1 WHERE u = 1 OR FALSE GROUP BY a", 1055},
	{"SELECT c FROM t1 WHERE u = pk GROUP BY a", 1055},
	{"SELECT c FROM t1 WHERE u = pk GROUP BY pk", 0},
	{"SELECT c FROM t1 WHERE u = pk GROUP BY u", 0},
	{"SELECT (SELECT c FROM t1 x WHERE x.pk = t1.a) FROM t1 GROUP BY a", 0},
	{"SELECT (SELECT c FROM t1 x WHERE x.pk = a) FROM t1 GROUP BY a", 0},
	{"SELECT (SELECT c FROM t1 x WHERE x.pk = t1.b) FROM t1 GROUP BY a", 1055},
	{"SELECT (SELECT MAX(x.c + t1.b) FROM t1 x) FROM t1 GROUP BY a", 1055},
	{"SELECT (SELECT MAX(x.c) + t1.b FROM t1 x) FROM t1 GROUP BY a", 1055},
	{"SELECT (SELECT MAX(t1.b) FROM t1 x) FROM t1 GROUP BY a", 0},
	{"SELECT (SELECT t1.b FROM t1 x LIMIT 1) FROM t1 GROUP BY a", 1055},
	{"SELECT (SELECT COUNT(*) FROM t1 x GROUP BY x.a HAVING x.a = t1.b LIMIT 1) FROM t1 GROUP BY a", 1055},
	{"SELECT (SELECT COUNT(*) FROM t1 x WHERE x.a = t1.b GROUP BY x.a LIMIT 1) FROM t1 GROUP BY a", 1055},
	{"SELECT (SELECT x.b FROM (SELECT b FROM t1 y WHERE y.pk = t1.b) x LIMIT 1) FROM t1 GROUP BY a", 1055},
	{"SELECT (SELECT x.b FROM (SELECT b FROM t1 y WHERE y.pk = t1.a) x LIMIT 1) FROM t1 GROUP BY a", 0},
	{"SELECT SUM(a) OVER (ORDER BY c) FROM t1 GROUP BY a, c", 0},
	{"SELECT SUM(a) OVER (ORDER BY c ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM t1 GROUP BY a", 1055},
	{"SELECT SUM(a) OVER (PARTITION BY c, b ORDER BY u) FROM t1 GROUP BY a", 1055},
	{"SELECT SUM(a) OVER (PARTITION BY a ORDER BY b, c) FROM t1 GROUP BY a", 1055},
	{"SELECT SUM(a) OVER (PARTITION BY MAX(c)) FROM t1 GROUP BY a", 0},
	{"SELECT SUM(a) OVER (PARTITION BY MAX(c) + b) FROM t1 GROUP BY a", 1055},
	{"SELECT a FROM t1 GROUP BY a WINDOW w AS (PARTITION BY a), w2 AS (PARTITION BY b)", 1055},
	{"SELECT a FROM t1 GROUP BY a WINDOW w AS (PARTITION BY a ORDER BY b)", 1055},
	{"SELECT a, FIRST_VALUE(b) OVER w FROM t1 GROUP BY a WINDOW w AS (ORDER BY c)", 1055},
	{"SELECT a, FIRST_VALUE(b) OVER (w) FROM t1 GROUP BY a WINDOW w AS (ORDER BY a)", 1055},
	{"SELECT a, MAX(b) OVER (w ORDER BY c) FROM t1 GROUP BY a WINDOW w AS (PARTITION BY a)", 1055},
	{"SELECT a, MAX(b) OVER () FROM t1 GROUP BY a", 1055},
	{"SELECT a, MAX(MAX(b)) OVER () FROM t1 GROUP BY a", 0},
	{"SELECT DISTINCT a FROM t1 ORDER BY t1.a", 0},
	{"SELECT DISTINCT t1.a FROM t1 ORDER BY a", 0},
	{"SELECT DISTINCT a AS b FROM t1 ORDER BY b", 0},
	{"SELECT DISTINCT a AS c FROM t1 ORDER BY c", 0},
	{"SELECT DISTINCT a AS c FROM t1 ORDER BY t1.c", 3065},
	{"SELECT DISTINCT a, b FROM t1 ORDER BY a + b", 0},
	{"SELECT DISTINCT a, b FROM t1 ORDER BY (SELECT MAX(x.c) FROM t1 x WHERE x.pk = t1.c)", 3065},
	{"SELECT DISTINCT a, b FROM t1 ORDER BY EXISTS (SELECT 1 FROM t1 x WHERE x.pk = t1.c)", 3065},
	{"SELECT DISTINCT a, b FROM t1 ORDER BY MAX(c)", 3029},
	{"SELECT DISTINCT a, MAX(c) FROM t1 GROUP BY a ORDER BY MAX(c)", 0},
	{"SELECT DISTINCT a, MAX(c) FROM t1 GROUP BY a ORDER BY MIN(c)", 0},
	{"SELECT DISTINCT a, MAX(c) FROM t1 GROUP BY a ORDER BY MAX(c) + 1", 0},
	{"SELECT DISTINCT a FROM t1 GROUP BY a ORDER BY b", 1055},
	{"SELECT DISTINCT a FROM t1 GROUP BY a ORDER BY a + 1", 0},
	{"SELECT DISTINCT a FROM t1 GROUP BY a, b ORDER BY a + b", 3065},
	{"SELECT DISTINCT a FROM t1 ORDER BY a DESC, RAND()", 0},
	{"SELECT DISTINCT x.a FROM t1 x JOIN t1 y ON x.pk = y.a ORDER BY y.a", 3065},
	{"SELECT DISTINCT x.a FROM t1 x JOIN t1 y ON x.pk = y.a ORDER BY x.a + y.a", 3065},
	{"SELECT DISTINCT x.* FROM t1 x JOIN t1 y ON x.pk = y.a ORDER BY y.a", 3065},
	{"SELECT DISTINCT x.* FROM t1 x JOIN t1 y ON x.pk = y.a ORDER BY x.c", 0},
	{"SELECT DISTINCT * FROM t1 x ORDER BY x.c", 0},
	{"SELECT DISTINCT d.a FROM (SELECT a, b FROM t1) d ORDER BY d.b", 3065},
	{"SELECT DISTINCT d.a FROM (SELECT a, b FROM t1) d ORDER BY d.a + 1", 0},
	{"SELECT DISTINCT d.a FROM (SELECT a + 1 AS a, b FROM t1) d ORDER BY d.a", 0},
	{"SELECT DISTINCT a FROM t1 ORDER BY ROW_NUMBER() OVER (ORDER BY b) + c", 3065},
	{"SELECT DISTINCT a FROM t1 ORDER BY 1 + 1", 0},
	{"SELECT DISTINCT a FROM t1 ORDER BY NULL", 0},
	{"SELECT DISTINCT a FROM t1 ORDER BY @v", 0},
	{"SELECT DISTINCT a FROM t1 ORDER BY $1", 0},
	{"SELECT DISTINCT a FROM t1 ORDER BY a LIMIT 1", 0},
	{"SELECT DISTINCT a FROM t1 ORDER BY (SELECT 1)", 0},
	{"SELECT a FROM t1 ORDER BY MAX(a) + 1", 3029},
	{"SELECT a FROM t1 ORDER BY ROW_NUMBER() OVER ()", 0},
	{"SELECT a FROM t1 ORDER BY (SELECT MAX(x.a) FROM t1 x)", 0},
	{"SELECT a FROM t1 ORDER BY (SELECT MAX(t1.a) FROM t1 x)", 3029},
	{"SELECT a FROM t1 ORDER BY COUNT(*) OVER ()", 0},
	{"SELECT MAX(a) FROM t1 ORDER BY COUNT(*)", 0},
	{"SELECT a FROM t1 GROUP BY a ORDER BY COUNT(*)", 0},
	{"SELECT a FROM t1 HAVING a > 0 ORDER BY COUNT(*)", 3029},
	{"SELECT a FROM t1 UNION SELECT a FROM t1 ORDER BY ROW_NUMBER() OVER ()", 3028},
	{"SELECT COUNT(*), c FROM t1 WHERE pk = 2 ORDER BY c", 0},
	{"SELECT COUNT(*) FROM t1 ORDER BY c", 0},
	{"SELECT COUNT(*) FROM t1 HAVING c > 0", 1054},
	{"SELECT * FROM t1 GROUP BY pk, a WITH ROLLUP", 1055},
	{"SELECT pk, a FROM t1 GROUP BY a, pk WITH ROLLUP", 0},
	{"SELECT pk FROM t1 GROUP BY pk, a WITH ROLLUP HAVING pk > 0", 0},
	{"SELECT pk FROM t1 GROUP BY pk WITH ROLLUP ORDER BY a", 1055},
	{"SELECT pk FROM t1 GROUP BY pk WITH ROLLUP ORDER BY pk", 0},
	{"SELECT pk + 1 FROM t1 GROUP BY pk + 1 WITH ROLLUP", 0},
	{"SELECT pk FROM t1 GROUP BY pk WITH ROLLUP ORDER BY GROUPING(pk)", 0},
	{"SELECT a, c FROM t1 GROUP BY a ORDER BY ANY_VALUE(c)", 1055},
	{"SELECT a, ANY_VALUE(c) FROM t1 GROUP BY a ORDER BY ANY_VALUE(c) + c", 1055},
	{"SELECT id FROM users u GROUP BY name HAVING (SELECT COUNT(*) FROM orders o WHERE o.user_id = u.id) > 0", 1055},
	{"SELECT a FROM t1 GROUP BY a HAVING (SELECT COUNT(*) FROM t1 x WHERE x.a = t1.a) > 0", 0},
	{"SELECT a FROM t1 GROUP BY a HAVING (SELECT COUNT(*) FROM t1 x WHERE x.a = t1.u) > 0", 1054},
	{"SELECT a FROM t1 GROUP BY a HAVING (SELECT COUNT(*) FROM t1 x WHERE x.a = u) > 0", 0},
	{"SELECT a FROM t1 GROUP BY a HAVING (SELECT COUNT(*) FROM t1 x WHERE x.a = c) > 0", 0},
	{"SELECT a FROM t1 GROUP BY a HAVING (SELECT COUNT(*) FROM t1 x WHERE x.pk = a) > 0", 0},
	{"SELECT a AS q FROM t1 GROUP BY a HAVING (SELECT COUNT(*) FROM t1 x WHERE x.pk = q) > 0", 0},
	{"SELECT c FROM t1 WHERE u = 1 GROUP BY a HAVING c > 0", 0},
	{"SELECT c FROM t1 WHERE u = 1 GROUP BY a HAVING b > 0", 1054},
	{"SELECT c FROM t1 WHERE pk = 1 GROUP BY a HAVING b > 0", 1054},
	{"SELECT c FROM t1 GROUP BY pk HAVING b > 0", 1054},
	{"SELECT c FROM t1 GROUP BY pk HAVING t1.b > 0", 1054},
	{"SELECT x.c FROM t1 x JOIN t1 y ON y.pk = x.a GROUP BY x.pk HAVING y.b > 0", 1054},
	{"SELECT x.c FROM t1 x JOIN t1 y ON y.pk = x.a GROUP BY x.pk HAVING MAX(y.b) > 0", 0},
	{"SELECT x.c FROM t1 x JOIN t1 y ON y.pk = x.a GROUP BY x.pk HAVING y.pk > 0", 1054},
}

func TestFullGroup(t *testing.T) {
	s, err := schema.Load(fullGroupSchema)
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range fullGroupCases {
		_, err := Analyze(s, c.sql)
		var e *Error
		switch {
		case err == nil && c.code == 0:
		case err == nil:
			t.Errorf("%s: accepted, want error %d", c.sql, c.code)
		case errors.As(err, &e) && e.Code == c.code:
		case errors.As(err, &e):
			t.Errorf("%s: error %d (%s), want %d", c.sql, e.Code, e.Message, c.code)
		default:
			t.Errorf("%s: %v, want %d", c.sql, err, c.code)
		}
	}
}

// TestFullGroupOracle checks fullGroupCases against a real mysqld: the error numbers must
// agree. Skipped without a mysqld on PATH (nix-shell -p mysql84).
func TestFullGroupOracle(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	o, err := oracle.Start(ctx, fullGroupSchema)
	if errors.Is(err, oracle.ErrNoServer) {
		t.Skip("no mysqld on PATH (nix-shell -p mysql84)")
	}
	if err != nil {
		t.Fatal(err)
	}
	defer o.Close()
	for _, c := range fullGroupCases {
		_, err := o.Describe(ctx, c.sql)
		var oe *oracle.Error
		got := 0
		if errors.As(err, &oe) {
			got = oe.Number
		} else if err != nil {
			t.Errorf("%s: %v", c.sql, err)
			continue
		}
		if got != c.code {
			t.Errorf("%s: the server says %d, the table %d", c.sql, got, c.code)
		}
	}
}
